import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import csharpIcon from '/public/csharp.svg'
import javaIcon from '/public/java.svg'
import javascriptIcon from '/public/logo-javascript.svg'
import pythonIcon from '/public/python-5.svg'
import gitIcon from '/public/git-icon.svg'
import reactIcon from '/public/react-2.svg'
import typescriptIcon from '/public/typescript.svg'
import nvimIcon from '/public/Neovim-mark.svg'
import vscodeIcon from '/public/visual-studio-code-1.svg'
import vsIcon from '/public/visual-studio-2013.svg'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
      <>
        <Head>
          <title>Evan&apos;s Portfolio</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="w-full h-screen px-10">
          <NavBar />
          <Hero />
          <Skills />
          <div className="border-2 w-full h-screen"></div>
        </div>
      </>
  );
};

const NavBar = () => {
  return (
      <div className="px-2 sm:px-4 py-3 rounded">
        <div className="container flex flex-wrap justify-between items-center mx-auto">
          <div className='flex flex-row items-center gap-2'>
            <Image src={csharpIcon} alt='charp' width={20} height={20}/>
            <h1 className='font-mono font-bold text-xl'>Evan</h1>
          </div>
          <a
              href="#about"
              className="block py-2 pr-4 pl-3 text-gray-700 rounded hover hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
          >
            About me
          </a>
          <a
              href="#skills"
              className="block py-2 pr-4 pl-3 text-gray-700 rounded hover hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
          >
            Skills
          </a>
          <a
              href="#experience"
              className="block py-2 pr-4 pl-3 text-gray-700 rounded hover hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
          >
            Experience
          </a>
          <a
              href="#projects"
              className="block py-2 pr-4 pl-3 text-gray-700 rounded hover hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
          >
            Projects
          </a>
          <a
              href="#contact"
              className="block py-2 pr-4 pl-3 text-gray-700 rounded hover hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
          >
            Contact Me
          </a>
        </div>
      </div>
  );
};

const Hero = () => {
  return (
      <div className="max-w-[1240px] w-full h-screen mx-auto p-2 flex justify-start items-center">
        <div>
          <p className="text-4xl font-bold">Hi! I&apos;m Evan!</p>
          <p className="text-4xl">
            I enjoy building applications to solve everyday problems I encounter.
          </p>
          <p className="text-xl">
            I enjoy tinkering and building solutions to increase productivity!
          </p>
        </div>
        <img
            className="h-60 rounded"
            src="https://live.staticflickr.com/7159/6416410061_dcbcc2fdaf_b.jpg"
            alt={'Profile pic'}
        ></img>
      </div>
  );
};

const Skills = () => {
  return (
      <div className="max-w-[1240px] w-full mx-auto p-2 flex justify-start items-center">
        <div>
          <h1 className="text-4xl font-bold pb-4">Skills</h1>
          <p className="text-xl pb-4">I have used:</p>
          <div className="flex flex-row">
            <ol className="flex flex-row gap-4">
              <SkillIcon name="C#" skillIcon={csharpIcon} />
              <SkillIcon name="Python" skillIcon={pythonIcon} />
              <SkillIcon name="Java" skillIcon={javaIcon} />
              <SkillIcon name="Typescript" skillIcon={typescriptIcon} />
              <SkillIcon name="Javascript" skillIcon={javascriptIcon} />
              <SkillIcon name="React" skillIcon={reactIcon} />
              <SkillIcon name="Git" skillIcon={gitIcon} />
            </ol>
          </div>
          <p className="text-xl pb-4 my-2">Tools</p>
          <div className="flex flex-row">
            <ol className="flex flex-row gap-4">
              <SkillIcon name="Neovim" skillIcon={nvimIcon} />
              <SkillIcon name="Visual Studio" skillIcon={vsIcon} />
              <SkillIcon name="VScode" skillIcon={vscodeIcon} />
            </ol>
          </div>
        </div>
      </div>
  );
};

interface SkillIconProps {
  name: string;
  skillIcon: string;
}

const SkillIcon = ({name,skillIcon}:SkillIconProps) => {
  return (
      <>
        <Image src={skillIcon} alt={name} width={50} height={50}/>
      </>
  )
}
export default Home;
