import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Evan's Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen px-10">
        <NavBar />
        <Hero />
        <Skills />
      </div>
    </>
  );
};

const NavBar = () => {
  return (
    <div className="px-2 sm:px-4 py-3 rounded">
      <div className="container flex flex-wrap justify-between items-center mx-auto">
        <a
          href="#about"
          className="block py-2 pr-4 pl-3 text-gray-700 rounded hover hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
        >
          About me
        </a>
        <a
          href="#skills"
          className="block py-2 pr-4 pl-3 text-gray-700 rounded hover hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
        >
          Skills
        </a>
        <a
          href="#experience"
          className="block py-2 pr-4 pl-3 text-gray-700 rounded hover hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
        >
          Experience
        </a>
        <a
          href="#projects"
          className="block py-2 pr-4 pl-3 text-gray-700 rounded hover hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
        >
          Projects
        </a>
        <a
          href="#contact"
          className="block py-2 pr-4 pl-3 text-gray-700 rounded hover hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
        >
          Contact Me
        </a>
      </div>
    </div>
  );
};

const Hero = () => {
  return (
    <div className="max-w-[1240px] w-full h-full mx-auto p-2 flex justify-start items-center">
      <div>
        <p className="text-2xl tracking-widest">
          Hi! I'm Evan and I enjoy building applications to solve everyday
          problems I encounter.
        </p>
        <p className="text-sm">
          I enjoy tinkering and building solutions to increase productivity!
        </p>
      </div>
    </div>
  );
};

const Skills = () => {
  return (
    <div>
      <p className="text-xl">Skills</p>
      <p>I have used:</p>
      <div className="flex flex-row">
        <ol className="flex flex-row gap-2">
          <li>C#</li>
          <li>Python</li>
          <li>Java</li>
          <li>Typescript</li>
          <li>React</li>
          <li>Git</li>
        </ol>
      </div>
    </div>
  );
};

export default Home;
